# Generated by Django 3.1.4 on 2020-12-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, null=True)),
                ('ip', models.CharField(max_length=16, unique=True)),
                ('ip_type', models.CharField(max_length=4)),
                ('continent_code', models.CharField(max_length=3)),
                ('continent_name', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=3)),
                ('country_name', models.CharField(max_length=50)),
                ('region_code', models.CharField(max_length=3)),
                ('region_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=7)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('geoname_id', models.IntegerField()),
                ('capital', models.CharField(max_length=50)),
                ('country_flag', models.URLField()),
                ('calling_code', models.CharField(max_length=10)),
                ('is_eu', models.BooleanField()),
            ],
        ),
    ]
